# SPDX-License-Identifier: Apache-2.0

name: Merge to Main

on:
  # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ "^1.17", "^1.18" ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Setup
        run: make setup
      #- name: Lint
      #  run: make lint
      - name: Lint
        run: make check-headers
      - name: Build
        run: make build
